[profile.default]
src = "src"
out = "out"
libs = ["lib"]

remappings = [
    "@account-abstraction/contracts/=node_modules/@account-abstraction/contracts",
    "@openzeppelin/contracts/=node_modules/@openzeppelin/contracts",
]

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
